### ISSUE TITLE
Katran not forwarding packets to tunnel interface

### ISSUE THREAD

**Issue by raitech12** [facebookincubator/katran#116] opened 2021-03-16 12:17 UTC
I just built katran tried to run a sample using grpc. 
I disabled hc_forwarding and added VIP and a real server but no packet is forwarded to the ipip0 interface and `katran_goclient -list_qm` shows nothing. However if I stop katran and I can see packets coming in using tcpdump.
How can trace the problem?

**Comment by udippant** [comment] 2021-03-16 22:22
`-list_qm` is to list QUIC specific mapping for a backend server's Id to its address ([as it says in the help message](https://github.com/facebookincubator/katran/blob/master/example_grpc/goclient/src/katranc/main/main.go#L64)).
Try just[ listing services](https://github.com/facebookincubator/katran/blob/master/example_grpc/goclient/src/katranc/main/main.go#L47) `katran_goclient -l`.

> but no packet is forwarded to the ipip0 interface

Are you checking this on the real server's interface or on the host running Katran? 

> However if I stop katran and I can see packets coming in using tcpdump

Katran runs in the XDP layer (NIC), which is before a packet traverses through the Kernel layer - which is when the tcpdump can capture the packets. Try running tcpdump on the real server.

**Comment by raitech12** [comment] 2021-03-17 16:44
Added VIP and Real server (VIP on LB machine: E.F.G.H, real server on A.B.C.D running nginx accessible on Internet from LB):
`./katran_goclient -A -t E.F.G.H:80`
`./katran_goclient -a -t E.F.G.H:80 -r A.B.C.D`

Set default gateway mac address in start script and created tunnel interfaces:
(nic: enp2s0)
`sysctl net.core.bpf_jit_enable=1`
`ip link add name ipip0 type ipip external`
`ip link add name ipip60 type ip6tnl external`
`ip link set up dev ipip0`
`ip link set up dev ipip60`
`ip a a 127.0.0.42/32 dev ipip0`


I checked config with `katran_goclient -l` and it is as expected.
Checking LRU stats with `katran_goclient -lru -s` shows packets missing.

I can't see any packets going through ipip0 tunnel interface with on the LB and Real Server machine
`tcpdump -nvi ipip0`

**Comment by raitech12** [comment] 2021-03-17 18:24
On LB: collect_debug_lb.sh
===
### links ###
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 xdpgeneric qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether d4:3d:7e:be:da:8e brd ff:ff:ff:ff:ff:ff
    prog/xdp id 96 tag 26a139a4021efccf jited
3: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: ipip0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd ::
6: ipip60@NONE: <NOARP,UP,LOWER_UP> mtu 1452 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd ::
### default route ###
default via E.F.100.33 dev enp2s0 proto static onlink
### neighbors ###
E.F.100.33 dev enp2s0 lladdr 0c:86:10:ed:35:2c REACHABLE
fe80::1 dev enp2s0 lladdr 0c:86:10:ed:35:2c router STALE
### ps ###
  74452 pts/1    S+     0:00 bash ./start_katran_grpc_server.sh
  74469 pts/1    S+     0:00 sudo sh -c /root/katran/_build/build/example_grpc/katran_server_grpc -balancer_prog=/root/katran/_build/deps/bpfprog/bpf/balancer_kern.o -intf=enp2s0 -hc_forwarding=false -v=9 -default_mac=0c:86:10:ed:35:2c
  74470 pts/1    S+     0:00 sh -c /root/katran/_build/build/example_grpc/katran_server_grpc -balancer_prog=/root/katran/_build/deps/bpfprog/bpf/balancer_kern.o -intf=enp2s0 -hc_forwarding=false -v=9 -default_mac=0c:86:10:ed:35:2c
  74471 pts/1    SLl+   0:01 /root/katran/_build/build/example_grpc/katran_server_grpc -balancer_prog=/root/katran/_build/deps/bpfprog/bpf/balancer_kern.o -intf=enp2s0 -hc_forwarding=false -v=9 -default_mac=0c:86:10:ed:35:2c
  74863 pts/6    S+     0:00 grep katran
### sysctl ###
kernel.bpf_stats_enabled = 0
kernel.unprivileged_bpf_disabled = 0
net.core.bpf_jit_enable = 1
net.core.bpf_jit_harden = 0
net.core.bpf_jit_kallsyms = 0
net.core.bpf_jit_limit = 264241152


On Real Server collect_debug_real.sh
======
### links ###
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eno1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master bond0 state UP mode DEFAULT group default qlen 1000
    link/ether 24:be:05:b6:46:a0 brd ff:ff:ff:ff:ff:ff
3: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 24:be:05:b6:46:a0 brd ff:ff:ff:ff:ff:ff
4: tunl0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
### default route ###
default via A.B.102.190 dev bond0 proto static metric 300
### neighbors ###
A.B.102.190 dev bond0 lladdr 68:3b:78:b8:76:41 DELAY
### sysctl ###
net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.bond0.arp_filter = 0
net.ipv4.conf.bond0.rp_filter = 1
net.ipv4.conf.default.arp_filter = 0
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.eno1.arp_filter = 0
net.ipv4.conf.eno1.rp_filter = 1
net.ipv4.conf.lo.arp_filter = 0
net.ipv4.conf.lo.rp_filter = 0
net.ipv4.conf.tunl0.arp_filter = 0
net.ipv4.conf.tunl0.rp_filter = 1
### iptables ###
Chain INPUT (policy ACCEPT 7073 packets, 100M bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 801 packets, 191K bytes)
 pkts bytes target     prot opt in     out     source               destination



katran_goclient -s -lru
========
summary: 78 pkts/sec. lru hit: 0.00% lru miss: 100.00% (tcp syn: 1.00% tcp non-syn: 0.00% udp: 0.00%) fallback lru hit: 78 pkts/sec
summary: 0 pkts/sec. lru hit: 0.00% lru miss: 0.00% (tcp syn: 0.00% tcp non-syn: 0.00% udp: 0.00%) fallback lru hit: 0 pkts/sec
summary: 0 pkts/sec. lru hit: 0.00% lru miss: 0.00% (tcp syn: 0.00% tcp non-syn: 0.00% udp: 0.00%) fallback lru hit: 0 pkts/sec
summary: 0 pkts/sec. lru hit: 0.00% lru miss: 0.00% (tcp syn: 0.00% tcp non-syn: 0.00% udp: 0.00%) fallback lru hit: 0 pkts/sec
summary: 0 pkts/sec. lru hit: 0.00% lru miss: 0.00% (tcp syn: 0.00% tcp non-syn: 0.00% udp: 0.00%) fallback lru hit: 0 pkts/sec
summary: 0 pkts/sec. lru hit: 0.00% lru miss: 0.00% (tcp syn: 0.00% tcp non-syn: 0.00% udp: 0.00%) fallback lru hit: 0 pkts/sec
summary: 0 pkts/sec. lru hit: 0.00% lru miss: 0.00% (tcp syn: 0.00% tcp non-syn: 0.00% udp: 0.00%) fallback lru hit: 0 pkts/sec


katran_goclient -l
=======
2021/03/17 19:19:47 vips len 1
VIP:        E.F.100.54 Port:     80 Protocol: tcp
Vip's flags:
 ->A.B.102.175   weight: 1 flags:
exiting


uname -a
====
Linux Ubuntu-2004-focal-64-minimal 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tehnerd** [comment] 2021-03-17 19:19
please follow up w/ instructions from EXAMPLE.md . "Configuration of forwarding plane" section. I'm at least can see that you did not disable rp_filter on real. nor you have enabled ipip0 interface on real w/ external type.

**Comment by tehnerd** [comment] 2021-03-17 19:20
https://github.com/facebookincubator/katran/blob/master/EXAMPLE.md

**Comment by raitech12** [comment] 2021-03-17 19:47
I tested on another real server because the first had some problems.

katran_goclient -l
=======
2021/03/17 20:43:15 vips len 1
VIP:        E.F.100.54 Port:     80 Protocol: tcp
Vip's flags:
 ->A.B.206.71    weight: 1 flags:
exiting

collect_debug_real.sh
=============
### links ###
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether fa:16:3e:cb:63:f4 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
3: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: ipip0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd :: permaddr 7e05:5fa0:6a2c::
6: ipip60@NONE: <NOARP,UP,LOWER_UP> mtu 1452 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd :: permaddr aa04:5e5b:ac8c::
### default route ###
default via A.B.200.1 dev ens3 proto dhcp src A.B.206.71 metric 100
### neighbors ###
A.B.200.1 dev ens3 lladdr 2a:f9:98:35:b2:37 REACHABLE
### sysctl ###
net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.arp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.ens3.arp_filter = 0
net.ipv4.conf.ens3.rp_filter = 0
net.ipv4.conf.ip6tnl0.arp_filter = 0
net.ipv4.conf.ip6tnl0.rp_filter = 0
net.ipv4.conf.ipip0.arp_filter = 0
net.ipv4.conf.ipip0.rp_filter = 0
net.ipv4.conf.ipip60.arp_filter = 0
net.ipv4.conf.ipip60.rp_filter = 0
net.ipv4.conf.lo.arp_filter = 0
net.ipv4.conf.lo.rp_filter = 0
net.ipv4.conf.tunl0.arp_filter = 0
net.ipv4.conf.tunl0.rp_filter = 0
### iptables ###
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination

**Comment by tehnerd** [comment] 2021-03-17 20:58
could please also show "ip address show" from real

**Comment by raitech12** [comment] 2021-03-17 21:01
### ip address show

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet E.F.100.54/32 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fa:16:3e:cb:63:f4 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    inet A.B.206.71/32 scope global dynamic ens3
       valid_lft 83247sec preferred_lft 83247sec
    inet6 fe80::f816:3eff:fecb:63f4/64 scope link
       valid_lft forever preferred_lft forever
3: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
4: ipip0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 127.0.0.42/32 scope host ipip0
       valid_lft forever preferred_lft forever
5: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd :: permaddr 7e05:5fa0:6a2c::
6: ipip60@NONE: <NOARP,UP,LOWER_UP> mtu 1452 qdisc noqueue state UNKNOWN group default qlen 1000
    link/tunnel6 :: brd :: permaddr aa04:5e5b:ac8c::
    inet6 fe80::a804:5eff:fe5b:ac8c/64 scope link
       valid_lft forever preferred_lft forever

**Comment by tehnerd** [comment] 2021-03-17 21:06
yeah. no more thoughts.
i see that you have some strange environment where ip addresses are allocated dynamicaly w/ /32
```
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
link/ether fa:16:3e:cb:63:f4 brd ff:ff:ff:ff:ff:ff
altname enp0s3
inet A.B.206.71/32 scope global dynamic ens3   << /32
```
not sure is it possible to collect any data from default router or not but i have no idea what else could be broken. mb @udippant  could have some ideas

**Comment by raitech12** [comment] 2021-03-17 21:18
Ok. I just setup another real server. No packets still coming to real

### links ###
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:ff:39:2d brd ff:ff:ff:ff:ff:ff
3: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 00:0c:29:ff:39:37 brd ff:ff:ff:ff:ff:ff
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: ipip0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
6: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd ::
7: ipip60@NONE: <NOARP,UP,LOWER_UP> mtu 1452 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd ::
### default route ###
default via A.B.244.94 dev ens160 proto static
### neighbors ###
A.B.244.94 dev ens160 lladdr 68:3b:78:b8:76:41 REACHABLE
### sysctl ###
net.ipv4.conf.all.arp_filter = 0
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.arp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.ens160.arp_filter = 0
net.ipv4.conf.ens160.rp_filter = 0
net.ipv4.conf.ens192.arp_filter = 0
net.ipv4.conf.ens192.rp_filter = 0
net.ipv4.conf.ip6tnl0.arp_filter = 0
net.ipv4.conf.ip6tnl0.rp_filter = 0
net.ipv4.conf.ipip0.arp_filter = 0
net.ipv4.conf.ipip0.rp_filter = 0
net.ipv4.conf.ipip60.arp_filter = 0
net.ipv4.conf.ipip60.rp_filter = 0
net.ipv4.conf.lo.arp_filter = 0
net.ipv4.conf.lo.rp_filter = 0
net.ipv4.conf.tunl0.arp_filter = 0
net.ipv4.conf.tunl0.rp_filter = 0
### iptables ###
Chain INPUT (policy ACCEPT 153M packets, 17G bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     all  --  ens160 *       0.0.0.0/0            0.0.0.0/0

Chain OUTPUT (policy ACCEPT 48M packets, 9542M bytes)
 pkts bytes target     prot opt in     out     source               destination



### IP addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet E.F.100.54/32 scope global lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0c:29:ff:39:2d brd ff:ff:ff:ff:ff:ff
    inet A.B.244.91/27 brd A.B.244.95 scope global ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:feff:392d/64 scope link
       valid_lft forever preferred_lft forever
3: ens192: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0c:29:ff:39:37 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::20c:29ff:feff:3937/64 scope link
       valid_lft forever preferred_lft forever
4: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
5: ipip0@NONE: <NOARP,UP,LOWER_UP> mtu 1480 qdisc noqueue state UNKNOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
    inet 127.0.0.42/32 scope host ipip0
       valid_lft forever preferred_lft forever
6: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd ::
7: ipip60@NONE: <NOARP,UP,LOWER_UP> mtu 1452 qdisc noqueue state UNKNOWN group default qlen 1000
    link/tunnel6 :: brd ::
    inet6 fe80::d8a8:1ff:fe6f:d0d8/64 scope link
       valid_lft forever preferred_lft forever

**Comment by raitech12** [comment] 2021-03-17 23:26
maybe packets dropped in BPF. Is there any way to debug processing packets in BPF `katran/lib/bpf/balancer_kern.c`?

**Comment by tehnerd** [comment] 2021-03-18 00:25
```
summary: 78 pkts/sec. lru hit: 0.00% lru miss: 100.00% (tcp syn: 1.00% tcp non-syn: 0.00% udp: 0.00%) fallback lru hit: 78 pkts/sec
```

78 pkts were successfully sent. so does not looks liek it was dropped by bpf

**Comment by raitech12** [comment] 2021-03-18 12:32
Ok. I summarize my configuration to confirm:

A.B.C.D on the internet as LB running katran, E.F.G.H on the internet as Real Server

LB: running katran_grpc with gateway mac, A.B.C.D on LB nic: enp2s0 , bpf_jit_enable=1, ipip0 with an IP, adding the IP as VIP and adding real server IP as real 

Server: bringing up ipip0 with an IP,  rp_filter=0, adding VIP on lo

**Comment by raitech12** [comment] 2021-03-18 13:14
I started testing LB and server on the same machine. No success

### Tesing 127.0.0.1 as server (LB and server on same machine)
I run an apache server listening on port 80 and configure katran:
`./katran_goclient -A -t E.F.G.H:80`
`./katran_goclient -a -t E.F.G.H:80 -r 127.0.0.1`

### curl -I http://127.0.0.1  (from LB)
HTTP/1.1 200 OK
Date: Thu, 18 Mar 2021 13:08:59 GMT
Server: Apache/2.4.41 (Ubuntu)
Last-Modified: Thu, 18 Mar 2021 13:08:34 GMT
ETag: "2aa6-5bdcf4c059ea6"
Accept-Ranges: bytes
Content-Length: 10918
Vary: Accept-Encoding
Content-Type: text/html


### curl -I http://E.F.G.H/   (from a remote machine)
curl: (52) Empty reply from server



Does it make sense?

**Comment by tehnerd** [comment] 2021-03-18 16:41
no. 127.0.0.1 wont work by design. LB does not pass packet to kernel. it just reflect it back to default router after ipip encapsulation. with 127.0.0.1 as real, default router would receive a packet with destination 127.0.0.1 and wont know where to forward it

**Comment by raitech12** [comment] 2021-03-19 21:47
After checking with my ISP, I found out that packets from source IP other than my LB are dropped.
I set the src IP address in `katran/lib/bpf/pckt_encap.h` file to be the LB IP but packets didn't being decapsulated.
Is there any way to decapsulate packets in real server?

**Comment by tehnerd** [comment] 2021-03-20 01:36
Could you show tcpdump from real. Where we can see packets from katran/lb.

**Comment by raitech12** [comment] 2021-03-20 07:08
tcpdump -nvvi any proto 4 or host E.F.100.54
tcpdump: listening on any, link-type LINUX_SLL (Linux cooked), capture size 262144 bytes

07:30:19.043222 IP (tos 0x0, ttl 49, id 257, offset 0, flags [none], proto IPIP (4), length 72)
    E.F.100.54 > A.B.244.65: IP (tos 0x0, ttl 115, id 5995, offset 0, flags [DF], proto TCP (6), length 52)
    X.Y.227.67.53387 > E.F.100.54.80: Flags [S], cksum 0xd3bf (correct), seq 1348903373, win 64240, options [mss 1360,nop,wscale 8,nop,nop,sackOK], length 0
07:30:20.049071 IP (tos 0x0, ttl 49, id 56704, offset 0, flags [none], proto IPIP (4), length 72)
    E.F.100.54 > A.B.244.65: IP (tos 0x0, ttl 115, id 5997, offset 0, flags [DF], proto TCP (6), length 52)
    X.Y.227.67.53387 > E.F.100.54.80: Flags [S], cksum 0xd3bf (correct), seq 1348903373, win 64240, options [mss 1360,nop,wscale 8,nop,nop,sackOK], length 0
07:30:22.044357 IP (tos 0x0, ttl 49, id 25460, offset 0, flags [none], proto IPIP (4), length 72)
    E.F.100.54 > A.B.244.65: IP (tos 0x0, ttl 115, id 6000, offset 0, flags [DF], proto TCP (6), length 52)
    X.Y.227.67.53387 > E.F.100.54.80: Flags [S], cksum 0xd3bf (correct), seq 1348903373, win 64240, options [mss 1360,nop,wscale 8,nop,nop,sackOK], length 0
07:30:26.045180 IP (tos 0x0, ttl 49, id 19530, offset 0, flags [none], proto IPIP (4), length 72)
    E.F.100.54 > A.B.244.65: IP (tos 0x0, ttl 115, id 6005, offset 0, flags [DF], proto TCP (6), length 52)
    X.Y.227.67.53387 > E.F.100.54.80: Flags [S], cksum 0xd3bf (correct), seq 1348903373, win 64240, options [mss 1360,nop,wscale 8,nop,nop,sackOK], length 0
07:30:34.045768 IP (tos 0x0, ttl 49, id 25460, offset 0, flags [none], proto IPIP (4), length 72)
    E.F.100.54 > A.B.244.65: IP (tos 0x0, ttl 115, id 6014, offset 0, flags [DF], proto TCP (6), length 52)
    X.Y.227.67.53387 > E.F.100.54.80: Flags [S], cksum 0xd3bf (correct), seq 1348903373, win 64240, options [mss 1360,nop,wscale 8,nop,nop,sackOK], length 0
	

E.F.100.54 : LB (also VIP)
A.B.244.65 : Real Server
X.Y.227.67 : a client

**Comment by raitech12** [comment] 2021-03-20 14:27
When I remove VIP from real server and set LB's IP as the src instead of 172.16.x.x (in `katran/lib/bpf/pckt_encap.h`), I receive IPIP packets in the real server and they are now decapsulated.

**Comment by udippant** [comment] 2021-08-30 19:07
Closing. Feel free to reopen if you have further questions.

**Closed by udippant** 2021-08-30 19:07 UTC
